tech: openapi
name: OpenAPI
dependencies:
  - type: npm
    name: openapi-types
    example: openapi-types
  - type: npm
    name: openapi3-ts
    example: openapi3-ts
  - type: npm
    name: "@asteasolutions/zod-to-openapi"
    example: "@asteasolutions/zod-to-openapi"
  - type: npm
    name: openapi-typescript
    example: openapi-typescript
  - type: npm
    name: "@apidevtools/swagger-parser"
    example: "@apidevtools/swagger-parser"
  - type: golang
    name: github.com/go-openapi/runtime
    example: github.com/go-openapi/runtime
  - type: golang
    name: github.com/go-openapi/swag
    example: github.com/go-openapi/swag
  - type: php
    name: swagger-api/swagger-ui
    example: swagger-api/swagger-ui
  - type: python
    name: openapi
    example: openapi
  - type: ruby
    name: openapi_parser
    example: openapi_parser
  - type: rust
    name: openapi
    example: openapi
  - type: maven
    name: io.quarkus:quarkus-smallrye-openapi
    example: io.quarkus:quarkus-smallrye-openapi
files:
  - openapi.yaml
  - openapi.json
  - openapi.yml
