# Default Ignore Patterns
# These directories and files are always excluded from scanning
# Users can override or add patterns via .stack-analyzer.yml or --exclude flag

patterns:
  common:
    - "__fixtures__"
    - "__snapshots__"
  
  git:
    - ".git"
    - ".gitlab"
    - ".svn"
    # Note: .github is NOT ignored - needed to detect GitHub Actions
  
  python:
    - "venv"
    - ".venv"
    - "__pycache__"
    - ".pytest_cache"
    - ".ruff_cache"
    - ".mypy_cache"
    - ".tox"
    - ".coverage"
    - ".hypothesis"
    - ".eggs"
    - "*.egg-info"
    - ".pytype"
  
  nodejs:
    - "node_modules"
    - ".npm"
    - ".yarn"
    - ".pnp"
    - ".next"
    - ".nuxt"
    - ".vuepress"
  
  java:
    - ".gradle"
    - ".m2"
  
  dotnet:
    - "obj"
    - "packages"
  
  ruby:
    - ".bundle"
  
  rust:
    - "target"
  
  terraform:
    - ".terraform"
    - "terraform.tfstate.d"
  
  docker:
    - ".docker"
  
  cloud:
    - ".azure"
    - ".azure-pipelines"
    - ".vercel"
  
  cache:
    - ".cache"
    - ".artifacts"
    - ".assets"
  
  ide:
    - ".vscode"
    - ".idea"
    - ".devcontainer"
  
  ci:
    - ".semgrep"
    - ".release"
    - ".changelog"
  
  serverless:
    - ".serverless"
    - ".fusebox"
  
  database:
    - ".dynamodb"
  
  misc:
    - ".log"
    - ".metadata"
    - ".react-email"
