tech: trufflesecurity
name: Truffle Security
type: ci
dependencies:
  - type: docker
    name: trufflesecurity/trufflehog
    example: trufflesecurity/trufflehog
  - type: githubAction
    name: trufflesecurity/trufflehog
    example: trufflesecurity/trufflehog
